# Feature Scaling

# standardization

by feature scaling nature of the data remain same but magnitude is reduce it is done so that all the entity of dataset have same magnitude by standardization mean of the data become 0 and var 1 formula for this is Xnew=(Xi-Xmean)/std

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 
from sklearn.preprocessing import StandardScaler

In [3]:
df=pd.read_csv(r"C:\Users\Ruhan\Desktop\QWETRUM task1- Syed MAhad Ur Rayyan\Messy_Employee_dataset.csv")
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [6]:
df.isnull().sum()

Employee_ID            0
First_Name             0
Last_Name              0
Age                  211
Department_Region      0
Status                 0
Join_Date              0
Salary                 0
Email                  0
Phone                  0
Performance_Score      0
Remote_Work            0
dtype: int64

In [5]:
df["Salary"].fillna(df["Salary"].mean(),inplace=True)

In [8]:
ss=StandardScaler()
ss.fit(df[["Salary"]])

StandardScaler()

In [11]:
df["Salaryss"]=pd.DataFrame(ss.transform(df[["Salary"]]),columns=["x"])

In [12]:
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Salaryss
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True,-1.293384
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True,-1.011296
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True,0.152371
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True,-0.800058
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False,1.231340

In [13]:
df.describe()

              Age         Salary         Phone      Salaryss
count  809.000000    1020.000000  1.020000e+03  1.020000e+03
mean    32.484549   85155.056396 -4.942253e+09 -7.575639e-17
std      5.656860   19638.295389  2.817326e+09  1.000491e+00
min     25.000000   50047.320000 -9.994973e+09 -1.788595e+00
25%     25.000000   68811.232500 -7.341992e+09 -8.326508e-01
50%     30.000000   85155.056396 -4.943997e+09  0.000000e+00
75%     40.000000  100372.662500 -2.520391e+09  7.752746e-01
max     40.000000  119971.650000 -3.896086e+06  1.773763e+00

# Normalization

 by Normalization data is scaled between 0 and 1 formula for this is Xnew=(Xi-Xmean)/(MAXi-MINi)

In [15]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
mm=MinMaxScaler()
mm.fit(df[["Salary"]])

MinMaxScaler()

In [19]:
df["Salarymm"]=pd.DataFrame(mm.transform(df[["Salary"]]),columns=["x"])

In [20]:
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Salaryss,Salarymm
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True,-1.293384,0.139012
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True,-1.011296,0.218198
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True,0.152371,0.544854
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True,-0.800058,0.277495
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False,1.231340,0.847735

In [21]:
df.describe()

              Age         Salary         Phone      Salaryss     Salarymm
count  809.000000    1020.000000  1.020000e+03  1.020000e+03  1020.000000
mean    32.484549   85155.056396 -4.942253e+09 -7.575639e-17     0.502082
std      5.656860   19638.295389  2.817326e+09  1.000491e+00     0.280851
min     25.000000   50047.320000 -9.994973e+09 -1.788595e+00     0.000000
25%     25.000000   68811.232500 -7.341992e+09 -8.326508e-01     0.268346
50%     30.000000   85155.056396 -4.943997e+09  0.000000e+00     0.502082
75%     40.000000  100372.662500 -2.520391e+09  7.752746e-01     0.719711
max     40.000000  119971.650000 -3.896086e+06  1.773763e+00     1.000000

# Removing Duplicates

In [27]:
#for checking duplicate
df.duplicated()
# to drop duplicate
df.drop_duplicates()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Salaryss,Salarymm
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.650000,bob.davis@example.com,-1651623197,Average,True,-1.293384,0.139012
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.660000,bob.brown@example.com,-1898471390,Excellent,True,-1.011296,0.218198
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.900000,alice.jones@example.com,-5596363211,Good,True,0.152371,0.544854
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.990000,eva.davis@example.com,-3476490784,Good,True,-0.800058,0.277495
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.610000,frank.williams@example.com,-1586734256,Poor,False,1.231340,0.847735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David,Miller,30.0,HR-California,Active,8/19/2023,85155.056396,david.miller@example.com,-3546212759,Good,True,0.000000,0.502082
1016,EMP2016,David,Johnson,30.0,Cloud Tech-Texas,Inactive,11/7/2021,100215.060000,david.johnson@example.com,-2508261122,Good,True,0.767245,0.717458
1017,EMP2017,Charlie,Williams,40.0,Finance-New York,Active,10/4/2023,114587.110000,charlie.williams@example.com,-1261632487,Average,False,1.499442,0.922995
1018,EMP2018,Alice,Garcia,30.0,HR-Florida,Inactive,12/16/2024,71318.790000,alice.garcia@example.com,-8995729892,Good,True,-0.704901,0.304207
1019,EMP2019,Heidi,Jones,30.0,DevOps-Illinois,Pending,2/22/2021,77764.240000,heidi.jones@example.com,-7629745492,Average,False,-0.376532,0.396384

# Replace And Data Type Change

 to replace df.replace is used 
 to change datatype use astype